src/Component/Navbar.jsx
This PR enhances the visual and functional design of the `<nav>` component by:
- Adding a **glassy UI effect** using Tailwind's `backdrop-blur`, translucent background, and borders.
- Making the navbar **sticky** so it remains visible at the top of the page during scroll.
Fixes #<issue-number> 
---
---
- Verified the sticky behavior during scrolling in both desktop and mobile views.
- Confirmed visual improvements in Chrome and Firefox.
- Ensured responsiveness across screen sizes using Tailwind's utility classes.
- OS: macOS / Windows  
- Browser: Chrome v115, Firefox v115  
- Node: v18+  
- Framework: React + Tailwind CSS
---
---
- No additional dependencies introduced.
- Minor visual performance impact due to backdrop blur, which is negligible on modern browsers.
---
---
```jsx
<nav …
```
=> Added the ✨Glassy effect

data/freeCertificateCourses.js, src/App.jsx, src/Component/FreeCertificateCourses.jsx, src/Component/Navbar.jsx
**This PR adds a dedicated Certification Course section to the project. Key features include:**
1. A clean and responsive layout to display certification courses
2. UI cards containing course name, issuing authority, duration, and certificate link
3. Styled using existing design guidelines to maintain consistency
4. Mobile responsiveness and accessibility improvements
5. Code structured for easy future scalability (e.g., filtering/sorting)
I have tested the UI across different screen sizes and ensured smooth integration with the rest of the project.
🙋‍♂️ **Additional Note:**
I’m an intermediate-level MERN stack developer and would love to contribute more! Kindly assign me more issues such as:
- Enhancing About & Contact Sections
- Integrating EmailJS for a functional Contact form
Looking …
=> Added Free Certification Course section with UI enhancements

src/App.jsx, src/Component/BackToTop.jsx
Related Issue: #19 
**Feature:** Added "Back to Top" Button
**Description:**
I added a Back to Top button to improve user navigation. The button appears when the user scrolls down the page and smoothly scrolls back to the top when clicked.
**Where I added it:**
Created a new component: BackToTop.jsx inside the src/Component/ folder.
Imported and used <BackToTop /> in App.jsx so that it’s always visible on every page.
**Styling:**
The button has a clean, minimal look that matches theme of BuildOnCoffee.
It’s placed at the bottom-right corner and includes a smooth hover animation using Lucide’s ArrowUp icon.
=> Added back to top button for improved navigation

src/Component/FreeCertificateCourses.jsx, src/Component/HeroSection.jsx, src/Component/Navbar.jsx, src/Component/ToolCard.jsx, src/Component/WhatWeDoDifferently.jsx
**Date:** July 28, 2025
- ✨ Enhanced UI flow by removing extra steps when clicked on "Join our Community" button in the taskbar.
- ✨ToolCard cards are aligned left for readability.
- ✨Image and heading aligned side-by-side in Toolcard.
- ✨Improved simple but effective CSS hover stylings.
Crafted with love,
**Apekshaa Yadav**
(needs coffee ☕😞)
Let me know how you like it. Feel free to suggest anything else!
=> UI/UX: Layout improvements, enhanced UX (community styling fix), hover styling.

src/Component/About.jsx, src/index.css
This PR includes the following improvements:
- Redesigned the "About BuildOnCoffee" and "Why BuildOnCoffee?" sections for better visual hierarchy and consistency.
- Fixed page overflow issues across all routes to ensure consistent scrolling behavior and layout responsiveness.
- Ensured that changes do not break responsiveness across screen sizes.
Let me know if any adjustments are needed!
=> Fix styling of About section and overflow fixed.

src/Component/Contribute.jsx
Description
UI of the Contribute Page for the app enhanced.
Closes #44
=> Fix contribute page UI 44

package-lock.json, package.json, src/App.css, src/App.jsx, src/Component/HeroSection.jsx, src/Component/Navbar.jsx, src/context/ThemeContext.jsx, src/index.css, src/main.jsx, tailwind.config.js
Enhanced The Hero Section
Fixed the issue #66. 
Description:
Increased the height of the Hero Section to enhance its visual impact and create a more immersive first impression.
Implemented a fully responsive layout that adapts seamlessly across all screen sizes, including mobile, tablet, and desktop devices.
Added smooth entrance animations to headings, subheadings, and call-to-action elements to boost user engagement and interaction.
Integrated dynamic effects such as parallax scrolling, animated gradients, and floating decorative elements to add visual depth and richness.
Refined the typography and visual hierarchy to ensure the platform’s core message is communicated clearly and effectively.
Fixed and optimized the navigation bar for better responsiveness, alignment, and consistent …
=> Hero Section Enhancement #66

src/App.css
- ✅ Complete dark mode implementation for all components
- ✅ CSS custom properties for consistent theming
- ✅ Accessibility improvements (focus indicators, high contrast)
- ✅ Coffee-themed design elements
- ✅ Responsive design enhancements
- ✅ Loading states and smooth animations
- ✅ Professional component styling (cards, buttons, forms, tables)
The existing dark mode implementation was incomplete, lacking styles for many components and missing accessibility features. This enhancement provides a comprehensive styling system.
None - all changes are additive and backward compatible.
=> feat: enhance dark mode with complete styling system

src/Component/WhatWeDoDifferently.jsx
Changed what -we-do-differently section, added light/dark mode
issue #34 
Before 
After
=> update what we do differently  #34

src/Component/Footer.jsx
Enhancement—UI For the Footer Section #49
As per the design provided for the footer section, the footer UI is made.
Before :
After:
=> Enhancement - UI For the Footer Section #49

src/App.jsx, src/Component/JoinCommunity.jsx
added light/dark mode in join community section
issue #50
=> changed join communtiy section #50

data/courses.js, src/Component/CoursesList.jsx, src/Component/Notification.jsx, src/Component/ToolCard.jsx, src/utils/isNewItem.js
This PR introduces a notification popup and a "NEW" badge feature to highlight newly added courses.
**Changes Made:**
->Added Notification.jsx
->Displays a popup at the top (between navbar and "All Courses") showing the count of newly added courses.
->Auto hides after 7 seconds.
**Updated CoursesList.jsx**
->Integrated the Notification component.
->Calculated new courses added in the last 7 days.
**Updated ToolCard.jsx**
->Added a NEW badge on cards for newly added courses.
->Created isNewItem.js utility
->Helper function to check if a course is new (added in the last 7 days).
Preview:
📸 Before: (no notification or badges)
📸 After:
->Popup appears when new courses are added.
->"NEW" badge appears on course cards.
Checklist:
->Code follows project coding standards.
->No console errors or …
=> Added new course notification popup and NEW badge

src/Component/Contribute.jsx
changed dark classes to contribute page
before :
after:
fixes:#123
=> changed dark classes for contribute page #123

src/Component/FreeCertificateCourses.jsx
This PR addresses issue #135, where the card backgrounds on the "Courses with Free Certificates" page do not adapt to dark mode, retaining a light gray background. The fix ensures that the card backgrounds update to a suitable color in dark mode, providing sufficient contrast with the text and aligning with the theme for improved readability.
- Closes #135
- Updated the CSS for the card components on the "Courses with Free Certificates" page to dynamically adjust the background color based on the active theme (light/dark).
- Ensured the new background color in dark mode provides adequate contrast with the text for better readability.
- Tested the changes across different browsers and devices to confirm consistent behavior.
1. Navigate to …
=> Fix Card Color Issue in Dark Mode

src/Component/Navbar.jsx
**Enhancement: Improve Navigation UX**
fix issue #43 
This PR adds a modern navigation experience by:
Making the navbar sticky (position: fixed) to stay visible at the top
Adding shadow on scroll for visual depth
Implementing auto-hide on scroll down and show on scroll up using JavaScript
Using Tailwind classes for smooth transitions
merge it @anup2702
=> add sticky and auto-hide navbar with scroll behavior

src/App.jsx, src/Component/BackToTop.jsx, src/Component/Chatbot/BuildOnCoffeeChatbot.jsx
**Description:**
This PR refactors the floating button logic by:
- Moving both the Chatbot and Back-to-Top button positioning into a shared container within App.jsx.
- Removing redundant positioning and z-index classes from individual components to prevent UI overlap.
- Improving maintainability and consistency of floating elements across all pages.
**Why this is needed:**
Previously, each floating component managed its own absolute positioning, leading to overlap issues and layout inconsistencies. Centralizing their position control simplifies management and ensures proper stacking order.
**After Fix**
It fixes #164 
I'm ready to make any changes based on feedback.
=> fix(overlapping): consolidate floating button positioning in layout

src/Component/About.jsx, yarn.lock
- Add fade-in animations for better user experience
- Implement gradient backgrounds and decorative elements
- Improve layout and component structure
- Add interactive hover effects and transitions
**Screenshots after ui update**
It fixes #167 
Happy to discuss any feedback or make adjustments as needed.
=> feat(About): enhance About page with animations and improved styling

src/Component/JoinCommunity.jsx, src/Component/ToolsList.jsx
- Updated outdated Twitter button to the new X logo  
- Changed its color to black for brand consistency  
- Added LinkedIn button between GitHub and Discord links  
- Fixed incorrect import in `src/Component/ToolsList.jsx` (changed `motion/react` to `framer-motion` for proper build)  
- Ensured consistent styling for all social buttons  
This pull request **resolves issue #172**.
=> feat(community): update Twitter button, add LinkedIn, and set correct colors

data/roadmap.js, data/webDevRoadmap.js, src/App.jsx, src/Component/Roadmaps/WebDevRoadmap.jsx, src/Component/TermsOfService.jsx
This pull request introduces a completely redesigned and enhanced Terms of Service page to provide a clear,
transparent, and visually engaging user experience.
The new implementation focuses on modern UI/UX principles and reinforces our commitment to user privacy by
making the information easy to understand and navigate.
**Key Changes:**
- Modern & Animated UI: Implemented a new design using Tailwind CSS, featuring gradients, background blur
effects, and smooth animations to create a polished and professional look.
- Clear & Structured Content: The policy is broken down into logical, easy-to-read sections, each with a corresponding icon from lucide-react for better visual communication.
- Interactive Elements: The page includes hover effects and fade-in animations on load to improve user …
=> feat(ui): Redesign and Enhance Terms of Service Page

data/products.js, src/Component/Navbar.jsx, src/Component/ProductsSection.jsx
- Removed "Tools" and "Roadmap" from the Navbar as requested.
- Added Roadmap into the Products section.
- Adjusted layout and scroll behavior to ensure smooth horizontal navigation using arrows.
Linked to: #177
=> Navbar & Product Section Updates

data/glossary.js, data/products.js, src/App.jsx, src/Component/Glossary/Glossary.jsx
Description:
This PR introduces a dedicated Glossary page to help users understand key technical terms used across the platform. The page includes:
✅ Search functionality to quickly find terms
✅ Category filter for focused browsing (e.g., Frontend, Backend, DevOps, Security, AI/ML, etc.)
✅ Responsive UI with Tailwind CSS matching the existing theme
✅ Animated glossary cards with Framer Motion
✅ Scalable data structure using glossaryData.js
This improves accessibility for beginners and supports learning within context.
Styling and layout adapted to match project standards
✅ Closes
Closes #192
=> feat: implemented glossary category cards with navigation

data/mobileDevRoadmap.js, data/roadmap.js, src/App.jsx, src/Component/Roadmap.jsx, src/Component/Roadmaps/MobileDevRoadmap.jsx
This PR introduces a new learning roadmap for Mobile Development.
Changes:
* Added a new "Mobile Development" card to the roadmaps page.
* Created a new page for the Mobile Development roadmap.
* Added a route for the new page.
* Included a new icon for the Mobile Development roadmap.
This helps users who want to learn mobile development by providing a structured learning path.
It fixes #203 
I'm happy to discuss on it further
=> feat(roadmap): add mobile development roadmap with resources and components

src/Component/About.jsx, src/Component/BackToTop.jsx, src/Component/Chatbot/BuildOnCoffeeChatbot.jsx, src/Component/Contribute.jsx, src/Component/Footer.jsx, src/Component/FreeCertificateCourses.jsx, src/Component/HeroSection.jsx, src/Component/JoinCommunity.jsx, src/Component/Navbar.jsx, src/Component/PrivacyPolicy.jsx, src/Component/ProductsSection.jsx, src/Component/Profile.jsx, src/Component/TermsOfService.jsx, src/Component/WhatWeDoDifferently.jsx, src/index.css, tailwind.config.js
Reverts anup2702/build-on-coffee#217
=> Revert "UI UPDATED"

data/learningPaths.js, data/products.js, src/App.jsx, src/Component/Paths/PathDetail.jsx, src/Component/Paths/PathsLanding.jsx
- Implement paths landing page with search and filtering
- Add path detail page with milestone tracking
- Include local storage for saving progress
- Add paths to products navigation
**Screenshots**
It fixes #205 
=> feat(paths): add learning paths feature with progress tracking

src/App.jsx
**PR Title** : SignUp import error fixed
**PR Description**  : This PR introduces a change in the import path error previously encountered upon deployment in Linux server at Vercel. 
The import path for Signup.jsx has been fixed and now it will work on Linux server as well .
**Causes behind error** : The filepath error was mainly due to case sensitive mismatch of SignUp.jsx instead of Signup.jsx  as the import path in App.jsx that works fine on Windows system but fails on Unix based OS driven systems such as Linux server , Linux Desktop, MAC etc.
This PR closes issue #237
=> Fixed the Signup component import error

data/cybersecurityRoadmap.js, data/roadmap.js, src/App.jsx, src/Component/Roadmap.jsx, src/Component/Roadmaps/CybersecurityRoadmap.jsx
- Add new cybersecurity roadmap entry to roadmap data
- Include Shield icon for cybersecurity roadmap
- Create new CybersecurityRoadmap component with step tracking
- Add comprehensive cybersecurity steps data with resources and videos
- Update App.jsx to include new cybersecurity route
It fixes #230  
Note: It also fixes the path error that occured after #251 
=> feat(roadmap): add cybersecurity roadmap with resources and components

data/cloudComputingRoadmap.js, data/learningPaths.js, data/roadmap.js, data/uiUxDesignRoadmap.js, src/App.jsx, src/Component/Roadmap.jsx, src/Component/Roadmaps/CloudComputingRoadmap.jsx, src/Component/Roadmaps/UiUxDesignRoadmap.jsx
This PR introduces a new learning path: "Backend Developer in 30 Days".
The new path provides a structured 30-day curriculum for aspiring backend developers, covering:
- Introduction to backend development and Node.js basics.
- Building REST APIs with Express.js.
- Database fundamentals (SQL/NoSQL) and ORM integration.
- Authentication, authorization, and API testing.
- Deployment basics and an introduction to microservices.
This addition aims to expand the available learning resources and provide a clear roadmap for users interested in backend development.
It fixes #236 
=> feat: Add Backend Developer in 30 Days learning path

data/learnToolsList.js, src/Component/Tools/LearnTools.jsx, vite.config.js
Fix: Resolve tools page icons not displaying properly
This pull request fixes the issue where icons were not displaying properly on the website. The problem was caused by missing asset configuration in the Vite build setup, preventing SVG icons and other assets from loading correctly.
The fix includes:
- Updated Vite configuration to properly handle SVG assets
- Added proper asset inclusion settings for icon libraries
- Ensured all icon dependencies are correctly configured
- Verified that icons display properly across all pages
Fixes #249 
Icons not displaying properly on the website
All icons displaying correctly with proper asset loading
This fix ensures that all SVG icons and assets load properly in the Vite build environment. The website should now display all icons correctly across …
=> Fixed icons on website 

src/Component/Paths/PathsLanding.jsx, src/Component/Roadmap.jsx
Changes made:
Added loading state + useEffect for the delay (1.2s).
While loading, shows a centered spinner.
After that, the original content appears.
PathsLanding file changed for this.
Duplicate icon entry in roadmap was giving an error so resolved that bug too
=> issue #291 show loading for data fetching

data/dsa.js, data/html.js, data/products.js, package-lock.json, src/App.jsx, src/Component/Quiz.jsx
Adding a Quiz page for topicwise quizzes and two sample quizzes
PR for #285
=> Adding quiz component

src/Component/BackToTop.jsx
Issue No: #299 
This PR adds a floating Back to Top button. The button features an orange accent background with a gradient and glow effect to match the styling of the BuildOnCoffee AI Assistant button
=> Restyled Back to Top Button

package-lock.json, package.json, src/Component/CoursesList.jsx, src/Component/ToolCard.jsx
=> Fix: favourites feature with Rollup build issue resolved

src/Component/AchievementBanner.css, src/Component/AchievementBanner.jsx, src/Component/Badge.css, src/Component/Badge.jsx, src/Component/ChallengeCard.css, src/Component/ChallengeCard.jsx, src/Component/CoursesList.jsx, src/Component/Leaderboard.css, src/Component/Leaderboard.jsx, src/Component/Profile.jsx, src/Component/ProgressBar.css, src/Component/ProgressBar.jsx, src/Component/ProjectsGallery.jsx, src/Component/Quiz.jsx, src/Component/context/AuthContext.jsx
This PR introduces comprehensive gamification features, user authentication integration, and UI improvements to the project. Key changes include:
Gamification Features:
Achievement badges for quiz performance and user actions
Challenge acceptance and referral badges
Progress tracking for courses
Interactive UI elements for course suggestions, challenges, and referrals
User Management:
Integration with Clerk for authentication
User-specific data management for badges, progress, and challenges via AuthContext.jsx
Enhanced profile page displaying user info, badges, progress, and accepted challenges (Profile.jsx)
UI Enhancements:
New components: AchievementBanner, Badge, ChallengeCard, Leaderboard, ProgressBar
Improved layout and visual feedback for achievements
Screenshots
Please add …
=>  Gamification, User Management, and UI Enhancements

package-lock.json, src/Component/Auth/Login.jsx, src/Component/Auth/Signup.jsx
Improve visual design of signup page with modern styling, better spacing, and dark mode compatibility. Add descriptive subtitle and enhance error message display. Update button and input styles for consistency.
It fixes #265 
=> feat(auth): update signup page styling and dark mode support

README.md
**📌 Description:**
This PR updates the README to clarify the environment setup required for running the project locally.
1-Added instructions for creating a .env file in the root directory
2-Documented how to obtain the Clerk Publishable Key from the Clerk Dashboard
VITE_CLERK_PUBLISHABLE_KEY=your_clerk_publishable_key
**This helps avoid the runtime error:**
Uncaught Error: Add your Clerk Publishable Key to the .env file
=> docs: add Clerk publishable key setup instructions

src/App.css, src/Component/Chatbot/BuildOnCoffeeChatbot.jsx
- Updated the search box behaviour to improve UI/UX.
- Removed the default scrollbar visibility.
- Scrollbar now appears only when the content exceeds the visible area.
- changed long placeholder value to concise, improvising the overall UI.
this PR solves #310
=> solves #310 : made scrollbar dynamic as input and enhanced placeholder text

data/learningPaths.js
This PR adds a new **60-day advanced learning path** focused on **System Design and Scalability**.  
It is designed for developers, senior engineers, and aspiring architects who want to **master distributed systems, scalability principles, and real-world architecture design**.  
The path emphasizes:  
- Core system design principles (scalability, reliability, availability)  
- High-level architecture design and trade-offs  
- Deep dives into system components (databases, caching, consensus, monitoring)  
- Case studies from top tech companies (Google, Netflix, Uber, Amazon, Twitter)  
- A final capstone project to design a **scalable e-commerce platform**  
This structured roadmap balances **theory, practical exercises, and case studies**, preparing learners for both **real-world …
=> Introduce 60-Day Advanced System Design & Scalability Path

data/javascript.js, package-lock.json, src/Component/Quiz.jsx
Include beginner, intermediate and advanced level questions to test JavaScript knowledge
Fix #346 
=> feat(quiz): add javascript questions to quiz component

data/javascript.js, data/nodejs.js, data/react.js, package-lock.json, src/Component/Quiz.jsx
Add a new set of Node.js questions covering beginner to advanced topics.
Include corresponding icon and description in the quiz selection interface.
It fixes #348
=> feat(quiz): add Node.js questions to quiz component

data/database.js, data/javascript.js, data/nodejs.js, data/react.js, package-lock.json, src/Component/Quiz.jsx
Add a new set of database questions covering SQL and NoSQL topics across beginner, intermediate, and advanced levels. This expands the quiz functionality to include database knowledge testing.
It fixes #349
=> feat(quiz): add database questions for quiz component

src/Component/CoursesList.jsx
- Closes #393 
- The changes are alignment of the progress box in white colors, now all the progress boxes are horizontally aligned with each other.
- Yes, I have tested the changes.
=> fixed issue of misalignment in the white boxes at the bottom of Courses

data/java.js, src/Component/Quiz.jsx
- Closes #392  - Add Java programming quiz content for beginners
This PR addresses the need for comprehensive Java learning materials for beginners by adding a structured quiz system. Java remains one of the most popular programming languages, and having interactive quiz content helps new developers:
- Test their understanding of fundamental concepts
- Practice core Java syntax and principles
- Build confidence through progressive difficulty levels
- Identify knowledge gaps in their learning journey
The quiz content progresses from basic syntax to beginner-level concepts, making it accessible for users just starting their Java programming journey.
Screenshot
- **Added `java.js` file**: Created comprehensive Java quiz data structure containing:
- Basic level questions covering Java syntax …
=> Added Java Quiz beginner to advanced

data/projectIdeas.json, src/Component/ProjectIdeas.jsx
=> feat: add description to project ideas

data/tailwindQuiz.js, src/Component/Quiz.jsx
This pull request introduces a new quiz on Tailwind CSS to the platform.
*   Added a new `tailwindQuiz.js` data file with questions covering Tailwind CSS fundamentals.
*   Updated the `Quiz.jsx` component to include the new quiz.
*   The quiz covers the following topics:
*   Core concepts of utility-first CSS.
*   Setup and configuration (`tailwind.config.js`).
*   Spacing, sizing, and typography utilities.
*   Flexbox and Grid utilities.
*   Responsive design (`sm`, `md`, `lg`, `xl` prefixes).
*   Hover, focus, and other state variants.
*   Dark mode.
*   Just-In-Time (JIT) compiler concepts.
*   Customizing themes and adding new utilities.
*   Using `@apply` for custom components.
1.  Navigate to the `/quiz` page.
2.  Select the "Tailwind CSS" quiz.
3.  Take the quiz and verify that the …
=> Feat: Add Tailwind CSS quiz

data/nextjsQuiz.js, src/Component/Quiz.jsx
This pull request introduces a new quiz on Next.js to the platform.
*   Added a new `nextjsQuiz.js` data file with questions covering Next.js fundamentals.
*   Updated the `Quiz.jsx` component to include the new quiz.
*   The quiz covers the following topics:
*   Pages and file-based routing
*   Server-Side Rendering (SSR) vs. Static Site Generation (SSG)
*   `getStaticProps` and `getServerSideProps`
*   API routes
*   Image optimization
*   Layouts and components
*   Dynamic routing
*   Client-side navigation (`next/link`, `next/router`)
*   Styling options (CSS Modules, Styled-jsx)
*   Deployment and Vercel
1.  Navigate to the `/quiz` page.
2.  Select the "Next.js" quiz.
3.  Take the quiz and verify that the questions and answers are correct.
This PR closes #386.
=> Feat: Add Next.js quiz

data/expressjsQuiz.js, src/Component/Quiz.jsx
This pull request introduces a new quiz on Express.js to the platform.
*   Added a new `expressjsQuiz.js` data file with questions covering Express.js fundamentals.
*   Updated the `Quiz.jsx` component to include the new quiz.
*   The quiz covers the following topics:
*   Core concepts (routing, middleware, request/response cycle)
*   Setting up an Express server
*   Handling GET, POST, PUT, DELETE requests
*   Working with route parameters and query strings
*   Implementing custom middleware
*   Error handling patterns
*   Serving static files
*   Template engines (e.g., EJS, Pug)
*   Building RESTful APIs
*   Best practices for security and performance
1.  Navigate to the `/quiz` page.
2.  Select the "Express.js" quiz.
3.  Take the quiz and verify that the questions and answers are …
=> Feat: Add Express.js quiz

data/typescriptQuiz.js, src/Component/Quiz.jsx
This pull request introduces a new quiz on TypeScript to the platform.
*   Added a new `typescriptQuiz.js` data file with questions covering TypeScript fundamentals.
*   Updated the `Quiz.jsx` component to include the new quiz.
*   The quiz covers the following topics:
*   Basic typing (string, number, boolean, any, unknown)
*   Arrays, tuples, and enums
*   Functions with type annotations and return types
*   Interfaces and type aliases
*   Classes, inheritance, and access modifiers
*   Generics (functions, classes, constraints)
*   Union and intersection types
*   Type inference and type assertions
*   Utility types (Partial, Pick, Readonly, Record, etc.)
*   TypeScript with React (props, state, generics in components)
*   Advanced concepts (decorators, namespaces, modules)
1.  Navigate …
=> Feat: Add TypeScript quiz

data/kubernetes.js, src/Component/Quiz.jsx
Hi @anup2702,
This PR introduces a new quiz for Kubernetes, as described in issue #406.
Kindly review this and add **GSSoC'25** and **Level 2** badges when merging.
=> feat: add kubernetes quiz (#406)

data/cloudNativeConcepts.js, src/Component/Quiz.jsx
Hi @anup2702,
This PR introduces a new quiz for Cloud-Native Concepts, as described in issue #409.
Kindly review this and add **GSSoC'25** and **Level 2** badges when merging.
=> feat: add cloud-native concepts quiz (#409)

src/Component/Quiz.jsx
=> feat(quiz): add CI/CD pipelines quiz and clean up quiz object formatting

data/webSecurityBasicsQuiz.js, package-lock.json, package.json, src/Component/Quiz.jsx
Add Web Security Basics Quiz Section  
---
This pull request implements a new "Web Security Basics Quiz" feature as requested in Issue #428. The quiz aims to validate developers' understanding of core web security concepts, promoting secure coding practices and raising awareness of common vulnerabilities.  
---
Current web development learning resources lack a dedicated, interactive quiz to reinforce foundational security knowledge. Developers may struggle to apply theoretical concepts (e.g., XSS, CSRF) to real-world scenarios, leading to insecure application practices. A targeted quiz addresses this gap by providing hands-on validation of understanding.  
---
A standalone quiz section covering critical web security topics, designed to:  
- Engage learners with interactive questions.  
- …
=> Introduce Web Security Basics Quiz (Resolves #428)

data/designPatternsQuiz.js, src/Component/Quiz.jsx
Implement Design Patterns Quiz (JS & React) (Fixes #430)  
This PR introduces a "Design Patterns in JavaScript & React Quiz" section to address Feature Request #430. The quiz provides structured practice for learners to reinforce knowledge of essential design patterns, fostering cleaner and more maintainable code in applications.  
- Added a new `DesignPatternsQuiz` component covering:  
- **JavaScript Patterns**: Singleton, Observer, Factory, Module.  
- **React Patterns**: Higher-Order Components (HOCs), Render Props, Custom Hooks.  
- **Best Practices**: Code reuse strategies (composition vs. inheritance, etc.).  
- Integrated with existing UI elements (`Navbar`, `Footer`) for consistent branding.  
- Added routing to `/design-patterns-quiz` for accessibility.  
Resolves #430
=> Add Design Patterns in JS & React Quiz (Resolves #430)
